### ISSUE TITLE
Inconsistent 404s for some URLs?

### ISSUE THREAD

**Issue by mikehearn** [adoptium/api.adoptium.net#1046] opened 2024-05-30 19:35 UTC
A user is reporting that the API is returning a 404 for them, for a release we know exists and the same URL does yield a successful download for me:

https://github.com/hydraulic-software/conveyor/issues/113

Is it possible that there is replication/sharding going on, and one shard has become inconsistent or stuck?

**Comment by karianna** [comment] 2024-05-31 01:59
Might be a region thing or a VPN thing?

**Comment by mikehearn** [comment] 2024-06-01 16:05
Maybe a region thing - that's what I was asking with inconsistent shards. I don't think this customer uses VPNs (and if they did, why would it matter?)

**Comment by karianna** [comment] 2024-06-03 09:11
> Maybe a region thing - that's what I was asking with inconsistent shards. I don't think this customer uses VPNs (and if they did, why would it matter?)

VPN might mean they're appearing to come from a different region (e.g., one that we're having challenges with on a given day)

**Comment by mikehearn** [comment] 2024-06-04 12:26
Is there a way to download the dataset in bulk and serve it myself as a fallback?

**Comment by karianna** [comment] 2024-06-05 03:38
> Is there a way to download the dataset in bulk and serve it myself as a fallback?

https://api.adoptium.net/q/swagger-ui/#/ has all of the API options, you might be able to script a wrapper around some of that?

**Comment by tellison** [comment] 2024-06-05 10:04
@mikehearn I see in your  log:
`wget https://api.adoptopenjdk.net/v3/binary/latest/22/ga/windows/x64/jdk/hotspot/normal/adoptopenjdk`

While we do have redirects in place, the old AdoptOpenJDK API is deprecated and you should preferably be going directly to `api.adoptium.net`, i.e.

`https://api.adoptium.net/v3/binary/latest/22/ga/windows/x64/jdk/hotspot/normal/eclipse`

In reality, I suspect that redirect is not causing the problem your user is experiencing. I also cannot reproduce the problem and agree that there is possibly an intermediary causing the 404.

**Comment by mikehearn** [comment] 2024-06-05 14:31
Is the only difference the domain name? If so then it should be easy enough to update.

**Comment by karianna** [comment] 2024-06-06 00:09
> Is the only difference the domain name? If so then it should be easy enough to update.

There are some subtle differences, but I'd start with that and see what falls out.

**Comment by johnoliver** [comment] 2024-06-13 12:36
This should be resolved as we have merged a fix in #1053 but in general the adoptium api was working in all regions at:

https://api.adoptium.net/v3/binary/latest/22/ga/windows/x64/jdk/hotspot/normal/eclipse

and it was purely an api.adoptopenjdk.net issue. api.adoptopenjdk.net is deprecated, so even going forward you should migrate.

**Comment by karianna** [comment] 2024-06-14 10:21
Closing now that #1053 has landed.

**Closed by karianna** 2024-06-14 10:21 UTC
Labels: bug

**Comment by mikehearn** [comment] 2024-06-14 14:51
Thanks.

**Comment by mikehearn** [comment] 2024-06-14 15:59
If I understand correctly, there is no documentation or any other guidance on how to migrate from one domain name to the other? I just tried to do it and I'm getting a 404 for:

https://api.adoptium.net/v3/binary/latest/17/ga/mac/x64/jdk/hotspot/normal/adoptopenjdk

It's unclear why, as the URL appears to have the same form as the example given above. api.adoptopenjdk.net works just fine. Nor is there any hint of differences. The README states only that the old API is deprecated due to a rebrand, so the fact that it appears to have a different backend and gives different answers is a surprise.

This is a great service that's very useful to the JVM community, but I have to say, if you want people to do new work for some obscure reason (what was wrong with the old name anyway), it would really help to have some tutorial on how to migrate. Neither the API website nor the README give any hint of differences but there must be some!

**Comment by karianna** [comment] 2024-06-15 00:27
https://api.adoptium.net will take you to the swagger UI definition, that should give you what the new target URL should be, in your case it should be https://api.adoptium.net/v3/assets/latest/17/hotspot?architecture=x64&image_type=jdk&os=mac&vendor=eclipse - point taken on migration in the future.
